export const employeesDetails = [
  {
    profileImage: "",
    name: "Mary Agbo",
    jobTitle: "Team Lead",
    department: "Sales&Marketing",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
  {
    profileImage: "",
    name: "Okafor Awele",
    jobTitle: "HR Admin",
    department: "Human Resource",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
  {
    profileImage: "",
    name: "James Deo",
    jobTitle: "Asst.HR admin",
    department: "Human Resource",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
  {
    profileImage: "",
    name: "Akin Luke",
    jobTitle: "Product Manger",
    department: "Customer Service",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
  {
    profileImage: "",
    name: "Mary Agbo",
    jobTitle: "Team Lead",
    department: "Sales&Marketing",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
  {
    profileImage: "",
    name: "Mary Agbo",
    jobTitle: "Team Lead",
    department: "Sales&Marketing",
    startDate: "23/03/2020",
    status: ["active", "on-leave", "stand-in", "suspended", "onboarded"],
  },
];
